"""
SendGrid Email Client

Provides send_email() for the onboarding pipeline.
All configuration is read from environment variables.
"""

from __future__ import annotations

import os

from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from shared.logger import logger


class EmailClientError(Exception):
    """Raised when an email fails to send."""


class EmailBounceError(EmailClientError):
    """Raised specifically when the email bounces (4xx recipient error)."""


def send_email(
    to_email: str,
    subject: str,
    body_html: str,
    *,
    from_email: str | None = None,
) -> dict:
    """
    Send an email via SendGrid.

    Parameters
    ----------
    to_email : str
        Recipient address.
    subject  : str
        Email subject line.
    body_html : str
        HTML body content. Plain-text fallback is auto-generated by SendGrid.
    from_email : str | None
        Sender address. Defaults to EMAIL_FROM env var.

    Returns
    -------
    dict
        ``{"status_code": int, "message_id": str}``

    Raises
    ------
    EmailBounceError
        If the API returns a 4xx indicating an invalid/bounced recipient.
    EmailClientError
        For any other send failure.
    """
    sender = from_email or os.environ["EMAIL_FROM"]
    api_key = os.environ["SENDGRID_API_KEY"]

    message = Mail(
        from_email=sender,
        to_emails=to_email,
        subject=subject,
        html_content=body_html,
    )

    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        status = response.status_code

        logger.info(
            "Email sent → %s  (status %s, subject: %s)",
            to_email,
            status,
            subject,
        )

        if 400 <= status < 500:
            raise EmailBounceError(
                f"Email to {to_email} returned status {status} — likely bounced."
            )

        if status >= 500:
            raise EmailClientError(
                f"SendGrid server error {status} for {to_email}."
            )

        message_id = response.headers.get("X-Message-Id", "unknown")
        return {"status_code": status, "message_id": message_id}

    except (EmailBounceError, EmailClientError):
        raise
    except Exception as exc:
        logger.error("Email send failed → %s: %s", to_email, exc)
        raise EmailClientError(str(exc)) from exc
